### ISSUE TITLE
[2.x] Descriptions not shown

### ISSUE THREAD

**Issue by sanjayankur31** [vit-project/vit#203]
On 2.0.0b2 here: I *think* this is to do with the column width algorithm in use. 

I started a task with "b", and that added the "Active" column in the output. This seems to have removed the "description" column completely. Screenshot attached:

![descriptions-not-shown-vit](https://user-images.githubusercontent.com/102575/65044559-0290c380-d955-11e9-89d5-000684f9e06f.png)

When I stop the task, the "Active" column goes away, and the "description" column is again visible.

**Comment by sanjayankur31** [comment]
I think it's simply because the screen is not considered broad enough to show the next column, but maybe another column should be sacrificed? (or the requirement reduced to allow wrapping of text in description?)

**Comment by thehunmonkgroup** [comment]
There is already an algorithm to reduce column widths in this case, how narrow is your screen?

**Comment by sanjayankur31** [comment]
It's a 1920x1680 screen here on a Thinkpad E490 (specs here: https://www.lenovo.com/gb/en/laptops/thinkpad/edge-series/E490/p/22TP2TEE490)

**Comment by thehunmonkgroup** [comment]
This looks like a weird edge case when only a single column in the report is adjusted to be smaller. The adjustment algorithm is actually working properly and shrinking the column by the correct width, but for some reason the adjusted column's width is 1 column too wide to fit in the display area, and thus the rendering library hides the entire column.

Commit https://github.com/scottkosty/vit/commit/7f2e4ba7e3058dbc508255c1f935c9d5ef0400dc accounts for this edge case, and will hopefully work in all cases.

**Comment by sanjayankur31** [comment]
Just got on to 2.0.0 which should include the fix. Still seeing this, though.  Still seems to do with long descriptions.

![vit](https://user-images.githubusercontent.com/102575/66429660-649e8f00-ea10-11e9-8bc0-afc0c6dd6160.png)

**Comment by thehunmonkgroup** [comment]
As an experiment:
 * Close vit
 * Reduce the window horizontally 10 columns or so
 * Re-open vit and pull up a report that has the issue
 * Start adding 1 column at a time to the window width until the descriptions appear

How many columns do you need to add?

Also, have you customized the columns/labels of your ```next``` report?

**Comment by sanjayankur31** [comment]
Here is how it goes: screencast:

https://ankursinha.fedorapeople.org//misc/vit-screencast.webm

**Comment by thehunmonkgroup** [comment]
Not quite what I was hoping for. What we need is an initial width that *should* display the description, but doesn't. From there, slowly add one column at a time until the description appears -- how many columns do you need to add before it appears?

**Comment by sanjayankur31** [comment]
It doesn't quite happen like that---if I start from a small width and increase one by one, the description does show up eventually, even if the window isn't at full width. However, if the window is full width to start with, and vit is run, description does not show. 

In this next one, I started with column width at about 27 and increased the terminal width column by column. The description began to show at about 110 and then remained. The next column, urgency also showed and remained---correctly. Then, I maximised the terminal, ran vit again, and description (and urgency) do not show.

https://ankursinha.fedorapeople.org//misc/vit-screencast-2.webm

**Comment by thehunmonkgroup** [comment]
From my earlier comment

> What we need is an initial width that should display the description, but doesn't

So you're starting too narrow. VIT is *basically* behaving correctly as you're widening things out (although the calculation of the header display seems slightly off).

You need to start with the terminal window wide enough *before* you open VIT that the description should *initially* be displayed -- this is where the bug is, on an auto-calculated column width on initial report load. If you can get me a reproduceible problem, then we have a shot at fixing it.

**Comment by thehunmonkgroup** [comment]
OK, pretty sure I finally figured this out:
 * The reduction code limits how far a column can be reduced to a width of 20 columns (which we want for readability).
 * In your case, there was more than one column in the report that needed width reduction, but at least one of them hit the limit of the 20 column minimum
 * This left the table too wide by the total amount that those columns which hit the limit where NOT reduced.

The problem was solved rather simply by calling the resizing code recursively until the total width of the adjusted columns is not greater than the window width, or we run out of columns to adjust.

@sanjayankur31, please try out latest master and see if the problem is resolved for you. Do me a favor and test it out on both narrow and wide terminal widths.

**Comment by sanjayankur31** [comment]
I think it seems to work now. Here's when I started with the full width of the screen, and with half the width. 

![vit-full-screen-width](https://user-images.githubusercontent.com/102575/68027630-bf8f7300-fcaa-11e9-827a-a0087648dc7f.png)
![vit-half-sreen-width](https://user-images.githubusercontent.com/102575/68027632-bf8f7300-fcaa-11e9-8465-83cf1759d136.png)


I noticed something else: If I start with the full width and then reduce/expand the screen width, sometimes the column does not immediately appear. If I "redraw" with Ctrl-L, though, it comes back. Is that expected?

![vit-shrunk-then-expanded](https://user-images.githubusercontent.com/102575/68027660-d5049d00-fcaa-11e9-98cb-d3eea5520c66.png)

After hitting Ctrl L:

![vit-shrunk-expanded-redrawn](https://user-images.githubusercontent.com/102575/68027664-d8982400-fcaa-11e9-957d-331a3cd538a0.png)

Thanks a bunch! I'll wait for a new release and push an update to Fedora.

**Comment by thehunmonkgroup** [comment]
Glad it works for you!

I wasn't able to reproduce the fullscreen issue you reported. Here's what I did to test:

1. Start in fullscreen by hitting F11
2. Open vit
3. Notice that description is properly displayed
4. Hit F11 to shrink screen
5. Hit F11 again to expand to fullscreen, notice that description is properly displayed

If you're starting with some arbitrary width and manually expanding/contracting the window size, then I *think* long descriptions wouldn't render again until you got all the way back to the original width from the last open or refresh.

**Comment by mrVanDalo** [comment]
I'm using the master branch, and I still have that problem, but only for very long descriptions and in the active report.

Otherwise all other situations work fine now.

**Comment by thehunmonkgroup** [comment]
@mrVanDalo if you post a clear, reproducable example using the [test script](https://github.com/scottkosty/vit/blob/2.x/scripts/generate-dummy-install.sh), I could have a look at the issue.

**Comment by mrVanDalo** [comment]
https://gist.github.com/mrVanDalo/539384a9a68244b95e68af73757b070a

`vit` is fine but `vit active` lacks still of description.

Uh, and I use `vit` from the `master` branch `rev : 41d046e86c1ff73a95d78b66149e3fb30a6aac85`

**Comment by thehunmonkgroup** [comment]
Finally! This bug has been a rough one, but I believe I've finally slayed it...

The issue was that all the resizing logic  was happening *before* the logic to compare the width of the header against the width of the content. So in cases where the header was wider than the column content, the resizing logic was off by the total number of characters wider that all headers were compared to all columns. And when a column doesn't fit in the available display area, the underlying Urwid library hides the whole thing.

Since this situation is different on every report, and different based on the column content provided by the user, it was very difficult to track down.

Please try master now, and you should find that not only is the ```active``` report working, but the ```next``` report is now also properly displaying its last ```urgency``` column.

So glad I took one last pass it this sucker, it was driving me crazy!

**Comment by mrVanDalo** [comment]
Yes works like Charm ! :tada: 
Thank you @thehunmonkgroup

**Comment by jahagirdar** [comment]
When is the 2.01 release planned? I would like to see this fix on pypi

**Comment by thehunmonkgroup** [comment]
@jahagirdar we release when ready, you are welcome to install a development version if you'd like the latest features and bug fixes: https://github.com/vit-project/vit/blob/2.x/DEVELOPMENT.md#development

**Comment by crab-apple** [comment]
Does this commit depend on something else? I manually applied the changes in [7200949](https://github.com/vit-project/vit/commit/7200949214362139e8073b6ca1a58cc756b2ebd0) to my task_list.py file (and verified that such file is being used) but I still have this issue.

In my case the description column disappears exactly when a project name becomes long enough to wrap into two lines. However, descriptions long enough to wrap don't give any problem.

**Comment by thehunmonkgroup** [comment]
@crab-apple the fix you reference is now in the latest point release, along with other fixes. Please try that. If the bug persists, you can use https://github.com/vit-project/vit/blob/2.x/scripts/generate-dummy-install.sh to generate a test case that exhibits the bug behavior.
